FROM telegraf:1.15-alpine
LABEL Name=telegraf Maintainer="Jonathan Sloan"

RUN echo "*** installing packages ***" \
    && apk --no-cache add -y smartmontools apcupsd \
    && rm -rf /tmp/* /var/tmp/* /var/cache/apt/* /var/lib/apt/lists/*

COPY VERSION .
